### ISSUE TITLE
Gemma 2: ValueError: both hidden_act and hidden_activation are set

### ISSUE THREAD

**Issue by agravier** [EricLBuehler/mistral.rs#520] opened 2024-07-02 00:26 UTC
**Describe the bug**

I am not sure if that's a bug. Python3.10, M1.

```python
from mistralrs import Runner, Which, ChatCompletionRequest, Architecture

runner = Runner(
    Which.Plain(
        model_id="google/gemma-2-9b-it",
        repeat_last_n=64,
        tokenizer_json=None,
        arch=Architecture.Gemma,
    )
)
```

⇒ 

```
2024-07-02T00:24:23.550226Z  INFO mistralrs_core::pipeline::normal: Loading `tokenizer.json` at `google/gemma-2-9b-it`
2024-07-02T00:24:23.551602Z  INFO mistralrs_core::pipeline::normal: Loading `config.json` at `google/gemma-2-9b-it`
2024-07-02T00:24:24.112827Z  INFO mistralrs_core::pipeline::normal: Loading `generation_config.json` at `google/gemma-2-9b-it`
2024-07-02T00:24:24.612251Z  INFO mistralrs_core::pipeline::normal: Loading `tokenizer_config.json` at `google/gemma-2-9b-it`
2024-07-02T00:24:24.618411Z  INFO mistralrs_core::utils::normal: DType selected is F16.
2024-07-02T00:24:24.618808Z  INFO mistralrs_core::pipeline::normal: Loading model `google/gemma-2-9b-it` on cpu.
2024-07-02T00:24:24.620317Z  INFO mistralrs_core::pipeline::normal: Model config: Config { attention_bias: false, head_dim: 256, hidden_act: Some(GeluPytorchTanh), hidden_activation: Some(GeluPytorchTanh), hidden_size: 3584, intermediate_size: 14336, num_attention_heads: 16, num_hidden_layers: 42, num_key_value_heads: 8, rms_norm_eps: 1e-6, rope_theta: 10000.0, vocab_size: 256000, max_position_embeddings: 8192, use_flash_attn: false }
2024-07-02T00:25:25.335118Z  INFO mistralrs_core::utils::normal: DType selected is F16.
Traceback (most recent call last):
  File "/Users/agravier/projects/perso/arc/archi/tests/mistral.py", line 21, in <module>
    runner = Runner(
ValueError: both hidden_act and hidden_activation are set
```

**Latest commit**

mistralrs-metal==0.1.24, which should be commit [3198004](https://github.com/EricLBuehler/mistral.rs/commit/3198004a91d759976403473f66f08bbf81f51f5d)

**Comment by EricLBuehler** [comment] 2024-07-02 00:29
Looks like you selected the `Gemma` instead of the `Gemma2` architecture, this should work:
```py
from mistralrs import Runner, Which, ChatCompletionRequest, Architecture

runner = Runner(
    Which.Plain(
        model_id="google/gemma-2-9b-it",
        repeat_last_n=64,
        tokenizer_json=None,
        arch=Architecture.Gemma2,
    )
)
```
Docs: https://ericlbuehler.github.io/mistral.rs/pyo3/mistralrs.html#Architecture

**Comment by EricLBuehler** [comment] 2024-07-03 12:58
@agravier, closing this as I think it is not a bug, please feel free to reopen!

**Closed by EricLBuehler** 2024-07-03 12:58 UTC
Labels: bug, resolved, triaged

**Comment by agravier** [comment] 2024-07-03 13:34
Thank you @EricLBuehler, it's good now indeed. Do you have a discord or slack for questions where I am not sure if it's a bug, like that one, to avoid that I pollute the issue tracker? For instance now I have a new "problem", but it's very likely that I am the problem, so a beginners forum or channel somewhere would be more appropriate.

**Comment by EricLBuehler** [comment] 2024-07-03 13:38
Glad to hear that! For questions, I would recommend our [Discussions](https://github.com/EricLBuehler/mistral.rs/discussions) page, which is not in the issue tracker, so it is more suited for questions. There is a [Discord](https://discord.com/invite/SZrecqK8qw) server, too.
