### ISSUE TITLE
Error Running phi3v Example with Local Model

### ISSUE THREAD

**Issue by jiabochao** [EricLBuehler/mistral.rs#718] opened 2024-08-28 02:29 UTC
## Describe the bug

I'm encountering an error while running the phi3v example using a local model. Here's my code:

```rust
use either::Either;
use indexmap::IndexMap;
use std::{path::PathBuf, sync::Arc};
use tokio::sync::mpsc::channel;

use mistralrs::{
    Constraint, DefaultSchedulerMethod, Device, DeviceMapMetadata, LocalModelPaths, MistralRs,
    MistralRsBuilder, ModelDType, ModelPaths, NormalRequest, Request, RequestMessage, Response,
    Result, SamplingParams, SchedulerConfig, VisionLoaderBuilder, VisionLoaderType,
    VisionSpecificConfig,
};

/// Gets the best device, cpu, cuda if compiled with CUDA
pub(crate) fn best_device() -> Result<Device> {
    #[cfg(not(feature = "metal"))]
    {
        Device::cuda_if_available(0)
    }
    #[cfg(feature = "metal")]
    {
        Device::new_metal(0)
    }
}

fn setup() -> anyhow::Result<Arc<MistralRs>> {
    // Select a Mistral model
    let loader = VisionLoaderBuilder::new(
        VisionSpecificConfig {
            use_flash_attn: false,
            prompt_batchsize: None,
            topology: None,
        },
        None,
        None,
        Some("microsoft/Phi-3.5-vision-instruct".to_string()),
    )
    .build(VisionLoaderType::Phi3V);
    // Load, into a Pipeline
    let paths = Box::new(LocalModelPaths::new(
        PathBuf::from("Phi-3.5-vision-instruct/tokenizer.json"),
        PathBuf::from("Phi-3.5-vision-instruct/config.json"),
        PathBuf::from("Phi-3.5-vision-instruct/tokenizer_config.json"),
        vec![
            PathBuf::from("Phi-3.5-vision-instruct/model-00001-of-00002.safetensors"),
            PathBuf::from("Phi-3.5-vision-instruct/model-00002-of-00002.safetensors"),
        ],
        None,
        None,
        None,
        None,
        None,
        Some(PathBuf::from(
            "Phi-3.5-vision-instruct/generation_config.json",
        )),
        None,
        Some(PathBuf::from(
            "Phi-3.5-vision-instruct/preprocessor_config.json",
        )),
        Some(PathBuf::from(
            "Phi-3.5-vision-instruct/processor_config.json",
        )),
    )) as Box<dyn ModelPaths + 'static>;
    let pipeline = loader.load_model_from_path(
        &paths,
        &ModelDType::Auto,
        &best_device()?,
        false,
        DeviceMapMetadata::dummy(),
        None,
        None,
    )?;
    // let pipeline = loader.load_model_from_hf(
    //     None,
    //     TokenSource::CacheToken,
    //     &ModelDType::Auto,
    //     &best_device()?,
    //     false,
    //     DeviceMapMetadata::dummy(),
    //     None,
    //     None, // No PagedAttention.
    // )?;
    // Create the MistralRs, which is a runner
    Ok(MistralRsBuilder::new(
        pipeline,
        SchedulerConfig::DefaultScheduler {
            method: DefaultSchedulerMethod::Fixed(5.try_into().unwrap()),
        },
    )
    .build())
}

fn main() -> anyhow::Result<()> {
    let mistralrs = setup()?;

    let bytes = match reqwest::blocking::get(
        "https://d2r55xnwy6nx47.cloudfront.net/uploads/2018/02/Ants_Lede1300.jpg",
    ) {
        Ok(http_resp) => http_resp.bytes()?.to_vec(),
        Err(e) => anyhow::bail!(e),
    };
    let image = image::load_from_memory(&bytes)?;

    let (tx, mut rx) = channel(10_000);
    let request = Request::Normal(NormalRequest {
        messages: RequestMessage::VisionChat {
            images: vec![image],
            messages: vec![IndexMap::from([
                ("role".to_string(), Either::Left("user".to_string())),
                (
                    "content".to_string(),
                    Either::Left("<|image_1|>\nWhat is shown in this image? Write a detailed response analyzing the scene.".to_string()),
                ),
            ])],
        },
        sampling_params: SamplingParams::default(),
        response: tx,
        return_logprobs: false,
        is_streaming: false,
        id: 0,
        constraint: Constraint::None,
        suffix: None,
        adapters: None,
        tools: None,
        tool_choice: None,
        logits_processors: None,
    });
    mistralrs.get_sender()?.blocking_send(request)?;

    let response = rx.blocking_recv().unwrap();
    match response {
        Response::Done(c) => println!(
            "Text: {}, Prompt T/s: {}, Completion T/s: {}",
            c.choices[0].message.content.as_ref().unwrap(),
            c.usage.avg_prompt_tok_per_sec,
            c.usage.avg_compl_tok_per_sec
        ),
        Response::InternalError(e) => panic!("Internal error: {e}"),
        Response::ValidationError(e) => panic!("Validation error: {e}"),
        Response::ModelError(e, c) => panic!(
            "Model error: {e}. Response: Text: {}, Prompt T/s: {}, Completion T/s: {}",
            c.choices[0].message.content.as_ref().unwrap(),
            c.usage.avg_prompt_tok_per_sec,
            c.usage.avg_compl_tok_per_sec
        ),
        _ => unreachable!(),
    }
    Ok(())
}

```

- Error output

```
Error: data did not match any variant of untagged enum PhiRopeScalingConfig at line 142 column 3
```

Could someone please assist me in identifying what might be causing the issue?

## Latest commit or version

master branch

**Comment by EricLBuehler** [comment] 2024-08-28 10:10
@jiabochao the following works on my machine:
```
~/mistral.rs> cargo run --features cuda --example phi3v                                                                                                                                                 08/28/2024 06:06:47 AM
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.18s
     Running `target/debug/examples/phi3v`
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 85/85 [00:01<00:00, 99.09it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 507/507 [00:01<00:00, 343.64it/s]
Text: The image captures a striking scene of a group of ants, their bodies a vibrant orange that contrasts sharply with the black object they are navigating around. The ants, about twelve in total, are of varying sizes, some adorned with multiple legs that have been detached from their bodies. Their focus is directed upwards, their heads gleaming with a silver blue light that accentuates their diligent demeanor. The light casts long shadows around them, adding depth to the image and drawing attention to the intricate details of their forms. The black structure they are traversing is only a fraction of the image, its sharp edges cutting into the soft blur that surrounds the rest of the scene. The image is a testament to the complexity and majesty inherent in the natural world., Prompt T/s: 448.5714, Completion T/s: 35.496956
```

The commit I'm running is `4b8d539`. Can you please confirm the contents of the local file `Phi-3.5-vision-instruct/config.json`?

**Comment by jiabochao** [comment] 2024-08-28 10:23
I cloned the repository from Hugging Face, so it should have the same content as this file: https://huggingface.co/microsoft/Phi-3.5-vision-instruct/blob/main/config.json

- config.json
```json
{
  "_name_or_path": "Phi-3.5-vision-instruct",
  "architectures": [
    "Phi3VForCausalLM"
  ],
  "attention_dropout": 0.0,
  "auto_map": {
    "AutoConfig": "configuration_phi3_v.Phi3VConfig",
    "AutoModelForCausalLM": "modeling_phi3_v.Phi3VForCausalLM"
  },
  "bos_token_id": 1,
  "embd_layer": {
    "embedding_cls": "image",
    "hd_transform_order": "sub_glb",
    "projection_cls": "mlp",
    "use_hd_transform": true,
    "with_learnable_separator": true
  },
  "embd_pdrop": 0.0,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 3072,
  "img_processor": {
    "image_dim_out": 1024,
    "model_name": "openai/clip-vit-large-patch14-336",
    "name": "clip_vision_model",
    "num_img_tokens": 144
  },
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "max_position_embeddings": 131072,
  "model_type": "phi3_v",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "original_max_position_embeddings": 4096,
  "pad_token_id": 32000,
  "resid_pdrop": 0.0,
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "long_factor": [
      1.0800000429153442,
      1.1100000143051147,
      1.1399999856948853,
      1.340000033378601,
      1.5899999141693115,
      1.600000023841858,
      1.6200000047683716,
      2.620000123977661,
      3.2300000190734863,
      3.2300000190734863,
      4.789999961853027,
      7.400000095367432,
      7.700000286102295,
      9.09000015258789,
      12.199999809265137,
      17.670000076293945,
      24.46000099182129,
      28.57000160217285,
      30.420001983642578,
      30.840002059936523,
      32.590003967285156,
      32.93000411987305,
      42.320003509521484,
      44.96000289916992,
      50.340003967285156,
      50.45000457763672,
      57.55000305175781,
      57.93000411987305,
      58.21000289916992,
      60.1400032043457,
      62.61000442504883,
      62.62000274658203,
      62.71000289916992,
      63.1400032043457,
      63.1400032043457,
      63.77000427246094,
      63.93000411987305,
      63.96000289916992,
      63.970001220703125,
      64.02999877929688,
      64.06999969482422,
      64.08000183105469,
      64.12000274658203,
      64.41000366210938,
      64.4800033569336,
      64.51000213623047,
      64.52999877929688,
      64.83999633789062
    ],
    "short_factor": [
       1.08,
      1.1,
      1.1300000000000001,
      1.2800000000000002,
      1.3100000000000003,
      1.4500000000000004,
      1.4500000000000004,
      1.9500000000000008,
      2.030000000000001,
      2.4299999999999926,
      2.5699999999999896,
      2.9499999999999815,
      3.729999999999965,
      3.869999999999962,
      4.189999999999955,
      4.43999999999995,
      4.6399999999999455,
      4.979999999999938,
      5.159999999999934,
      5.279999999999932,
      5.759999999999922,
      5.889999999999919,
      5.889999999999919,
      5.969999999999917,
      6.089999999999915,
      6.2799999999999105,
      6.7699999999999,
      6.8899999999998975,
      7.109999999999893,
      7.129999999999892,
      7.179999999999891,
      7.289999999999889,
      7.339999999999888,
      7.559999999999883,
      7.619999999999882,
      7.69999999999988,
      7.879999999999876,
      7.879999999999876,
      7.879999999999876,
      7.939999999999875,
      7.949999999999875,
      7.979999999999874,
      8.19999999999987,
      8.439999999999864,
      8.469999999999864,
      8.589999999999861,
      8.809999999999857,
      8.999999999999853
    ],
    "type": "su"
  },
  "rope_theta": 10000.0,
  "sliding_window": 262144,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.38.1",
  "use_cache": true,
  "vocab_size": 32064,
  "_attn_implementation": "flash_attention_2"
}
```

**Comment by EricLBuehler** [comment] 2024-09-01 14:18
@jiabochao I was not able to reproduce the error with your code and a locally downloaded Phi3.5-V model, on master. After you run `git pull`, it should work.

Closing this now, please feel free to reopen!

**Closed by EricLBuehler** 2024-09-01 14:18 UTC
Labels: bug
